import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../core/app_controller.dart';
import '../widgets/common.dart';

class GamesScreen extends StatefulWidget{const GamesScreen({super.key});@override State<GamesScreen> createState()=>_GamesScreenState();}
class _GamesScreenState extends State<GamesScreen>{bool loading=true;List<Map<String,dynamic>> items=[];@override void initState(){super.initState();load();}Future<void>load()async{try{final catalog=await context.read<AppController>().api.serviceCatalog();final out=<Map<String,dynamic>>[];void walk(dynamic categories){if(categories is! List)return;for(final c0 in categories){if(c0 is! Map)continue;final c=Map<String,dynamic>.from(c0);final services=c['services'];if(services is List){for(final s0 in services){if(s0 is Map){final s=Map<String,dynamic>.from(s0);final kind='${s['main_category']??c['name']??''}';if(kind.toLowerCase().contains('game')||kind.contains('لعبة')||kind.contains('ترفيه')||'${s['code']??''}'.contains('game'))out.add(s);}}}walk(c['children']);}}walk(catalog['categories']);setState((){items=out;loading=false;});}catch(_){setState(()=>loading=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('الألعاب والخدمات الرقمية')),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(12),children:[if(loading)const Center(child:Padding(padding:EdgeInsets.all(30),child:CircularProgressIndicator())) else if(items.isEmpty)const PageCard(child:Text('لا توجد خدمات ألعاب رقمية متاحة حاليًا من الكتالوج.',textAlign:TextAlign.center)) else ...items.map((s)=>Padding(padding:const EdgeInsets.only(bottom:8),child:_Service(service:s)))])));
}
class _Service extends StatefulWidget{const _Service({required this.service});final Map<String,dynamic> service;@override State<_Service> createState()=>_ServiceState();}
class _ServiceState extends State<_Service>{bool busy=false;Future<void>buy()async{final s=widget.service;final app=context.read<AppController>();final fields=s['fields'] is List?List<Map<String,dynamic>>.from((s['fields'] as List).map((e)=>Map<String,dynamic>.from(e))):<Map<String,dynamic>>[];final payload=<String,dynamic>{};final ctrls=<String,TextEditingController>{};final requiredFields=fields.where((f)=>f['required']==true).take(4).toList();for(final f in requiredFields){final c=TextEditingController();ctrls['${f['key']}']=c;}final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:Text('${s['name']??'خدمة'}'),content:Column(mainAxisSize:MainAxisSize.min,children:[for(final f in requiredFields)Padding(padding:const EdgeInsets.only(bottom:7),child:TextField(controller:ctrls['${f['key']}'],decoration:InputDecoration(labelText:'${f['label']??f['key']}')))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('تنفيذ'))]));if(ok==true){for(final f in requiredFields)payload['${f['key']}']=ctrls['${f['key']}']!.text;setState(()=>busy=true);try{final r=await app.requestService(serviceId:int.parse('${s['id']}'),payload:payload);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r['status']=='failed'?'${r['error_message']??'فشل الطلب'}':'تم إرسال الطلب بنجاح')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{for(final c in ctrls.values)c.dispose();if(mounted)setState(()=>busy=false);}}}
@override Widget build(BuildContext context){final s=widget.service;return PageCard(child:ListTile(contentPadding:EdgeInsets.zero,leading:const CircleAvatar(backgroundColor:Colors.purpleAccent,child:Icon(Icons.gamepad,color:Colors.white)),title:Text('${s['name']??''}',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:12)),subtitle:Text('${s['description']??''}',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10)),trailing:FilledButton(onPressed:busy?null:buy,child:Text(busy?'...':'دخول'))));}}
