import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../core/app_controller.dart';
import '../models/models.dart';
import '../widgets/common.dart';

class ProductDetailScreen extends StatefulWidget{const ProductDetailScreen({super.key,required this.product});final Product product;@override State<ProductDetailScreen> createState()=>_ProductDetailScreenState();}
class _ProductDetailScreenState extends State<ProductDetailScreen>{int qty=1;Map<String,dynamic>? variant;bool adding=false;num get unit=>num.tryParse('${variant?['effective_price']??variant?['price_override']??(widget.product.salePrice??widget.product.price)}')??0;Future<void>add()async{setState(()=>adding=true);final app=context.read<AppController>();await Future<void>.delayed(Duration.zero);if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تمت إضافة ${widget.product.name} × $qty إلى السلة')));setState(()=>adding=false);}}
@override Widget build(BuildContext context){final p=widget.product;final images=p.gallery.isNotEmpty?p.gallery:[if(p.image!=null)p.image!];return Scaffold(appBar:AppBar(title:const Text('تفاصيل المنتج')),body:ListView(padding:const EdgeInsets.all(12),children:[if(images.isNotEmpty)SizedBox(height:270,child:PageView(children:[for(final u in images)ClipRRect(borderRadius:BorderRadius.circular(18),child:Image.network(u,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Center(child:Icon(Icons.image_not_supported,size:55,color:Colors.black26))))])),const SizedBox(height:12),PageCard(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(p.name,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),if(p.brand.isNotEmpty)Text(p.brand,style:const TextStyle(color:Colors.black54)),const SizedBox(height:6),Text('${unit.toStringAsFixed(2)} ${p.currency}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:AppColors.burgundy)),const SizedBox(height:6),Row(children:[const Icon(Icons.star,color:Colors.amber,size:18),Text(' ${p.rating}  •  ${p.reviewsCount} تقييم',style:const TextStyle(fontSize:11)),const Spacer(),Text('${p.stock} متاح',style:const TextStyle(fontSize:10,color:Colors.green,fontWeight:FontWeight.w800))]),if(p.description.isNotEmpty)...[const SizedBox(height:10),Text(p.description,textAlign:TextAlign.right,style:const TextStyle(fontSize:12,height:1.5))]])),if(p.variants.isNotEmpty)...[const SizedBox(height:10),SectionHeader(title:'اختر المقاس/اللون',color:AppColors.blue),const SizedBox(height:6),Wrap(spacing:6,runSpacing:6,children:[for(final v in p.variants)ChoiceChip(label:Text('${v['color']??''} ${v['size']??''}'.trim(),style:const TextStyle(fontSize:10)),selected:variant==v,onSelected:(_)=>setState(()=>variant=v))])],const SizedBox(height:12),Row(children:[IconButton(onPressed:qty>1?()=>setState(()=>qty--):null,icon:const Icon(Icons.remove_circle_outline)),Text('$qty',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17)),IconButton(onPressed:()=>setState(()=>qty++),icon:const Icon(Icons.add_circle_outline)),const Spacer(),Text('${(unit*qty).toStringAsFixed(2)} ${p.currency}',style:const TextStyle(fontWeight:FontWeight.w900))]),const SizedBox(height:10),SizedBox(height:48,width:double.infinity,child:FilledButton.icon(onPressed:adding?null:add,icon:const Icon(Icons.shopping_cart_outlined),label:Text(adding?'...':'إضافة إلى السلة',style:const TextStyle(fontWeight:FontWeight.w900))))]));}
}
