import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';
import 'package:provider/provider.dart';
import '../core/app_controller.dart';
import '../widgets/common.dart';
import 'notifications_screen.dart';

class SettingsScreen extends StatefulWidget{const SettingsScreen({super.key});@override State<SettingsScreen> createState()=>_SettingsScreenState();}
class _SettingsScreenState extends State<SettingsScreen>{final auth=LocalAuthentication();bool biometric=false;bool busy=false;
Future<void>toggleBiometric(bool v)async{if(v){try{final ok=await auth.authenticate(localizedReason:'تأكيد تفعيل حماية شبيك بالبصمة');if(!ok)return;}on PlatformException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message??'البصمة غير متاحة')));return;}}setState(()=>biometric=v);}
@override Widget build(BuildContext context){final app=context.watch<AppController>();return Scaffold(appBar:AppBar(title:const Text('الإعدادات')),body:ListView(padding:const EdgeInsets.all(12),children:[PageCard(child:Column(children:[ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.person,color:AppColors.burgundy),title:Text(app.user?.name??'',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text(app.user?.phone??'')),ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.account_balance_wallet_outlined),title:const Text('رصيد المحفظة'),trailing:Text('${app.walletBalance.toStringAsFixed(2)} ر.ي',style:const TextStyle(fontWeight:FontWeight.w900,color:AppColors.burgundy))),SwitchListTile(contentPadding:EdgeInsets.zero,value:biometric,onChanged:busy?null:toggleBiometric,title:const Text('حماية بالبصمة',style:TextStyle(fontWeight:FontWeight.w800)),secondary:const Icon(Icons.fingerprint))])),const SizedBox(height:10),SectionHeader(title:'الحساب والتطبيق',color:Colors.slate),const SizedBox(height:6),PageCard(child:Column(children:[ListTile(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const NotificationsScreen())),leading:const Icon(Icons.notifications_none),title:const Text('الإشعارات')),ListTile(onTap:app.refreshAll,leading:const Icon(Icons.sync),title:const Text('تحديث بيانات الحساب')),ListTile(onTap:()=>showAboutDialog(context:context,applicationName:'شبيك | SHOPIK',applicationVersion:'1.0.0',applicationLegalese:'Yemen Code for Smart Technologies'),leading:const Icon(Icons.info_outline),title:const Text('عن التطبيق')),const Divider(),ListTile(onTap:()=>app.logout(),leading:Icon(Icons.logout,color:Colors.red.shade600),title:Text('تسجيل الخروج',style:TextStyle(color:Colors.red.shade600,fontWeight:FontWeight.w800))) ]))]));}}
