import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../core/app_controller.dart';
import '../models/models.dart';
import '../widgets/common.dart';
import 'orders_screen.dart';

class StoreScreen extends StatefulWidget { const StoreScreen({super.key}); @override State<StoreScreen> createState()=>_StoreScreenState(); }
class _StoreScreenState extends State<StoreScreen> {
  final search=TextEditingController(); final Map<int,int> cart={}; bool checkout=false;
  @override void dispose(){search.dispose();super.dispose();}
  num price(Product p)=>p.salePrice ?? p.price;
  Future<void> checkoutCart() async {
    final app=context.read<AppController>(); if(cart.isEmpty)return;
    if(app.addresses.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('أضف عنوان توصيل أولاً من الإعدادات أو العناوين.')));return;}
    final address=app.addresses.first;
    setState(()=>checkout=true);
    try{final items=cart.entries.map((e)=>{'product_id':e.key,'quantity':e.value}).toList(); final order=await app.api.createOrder(items:items,shippingAddress:Map<String,dynamic>.from(address),paymentMethod:'wallet'); setState(()=>cart.clear()); await app.refreshAll(); if(mounted){showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('تم إنشاء الطلب'),content:Text('رقم الطلب: ${order['order_number']??order['id']}'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('موافق'))]));}}
    catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>checkout=false);}
  }
  @override Widget build(BuildContext context){final app=context.watch<AppController>(); final q=search.text.trim().toLowerCase(); final visible=app.products.where((p)=>q.isEmpty||p.name.toLowerCase().contains(q)||p.slug.toLowerCase().contains(q)).toList(); return Scaffold(appBar:AppBar(title:const Text('متجر شبيك | سوق بلس'),actions:[IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OrdersScreen())),icon:const Icon(Icons.receipt_long))]),body:RefreshIndicator(onRefresh:app.refreshAll,child:ListView(padding:const EdgeInsets.all(12),children:[PageCard(child:TextField(controller:search,onChanged:(_)=>setState((){}),textDirection:TextDirection.rtl,decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'ابحث في المنتجات والمتاجر...',isDense:true))),const SizedBox(height:10),if(app.vendors.isNotEmpty)SizedBox(height:46,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:app.vendors.length,itemBuilder:(_,i){final v=app.vendors[i];return Chip(avatar:const Icon(Icons.store,size:16),label:Text('${v['store_name']??v['name']??'متجر'}',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w800)));},separatorBuilder:(_,__)=>const SizedBox(width:5))),const SizedBox(height:10),if(visible.isEmpty)const PageCard(child:Text('لا توجد منتجات متاحة من الخادم.',textAlign:TextAlign.center)) else GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:visible.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:9,mainAxisSpacing:9,childAspectRatio:.73),itemBuilder:(_,i)=>_ProductCard(product:visible[i],quantity:cart[visible[i].id]??0,onAdd:(){setState(()=>cart[visible[i].id]=(cart[visible[i].id]??0)+1);},onRemove:(){setState((){final n=(cart[visible[i].id]??0)-1;if(n<=0)cart.remove(visible[i].id);else cart[visible[i].id]=n;});}})),const SizedBox(height:90)])),bottomSheet:cart.isEmpty?null:SafeArea(child:Container(padding:const EdgeInsets.all(10),decoration:const BoxDecoration(color:Colors.white,boxShadow:[BoxShadow(blurRadius:10,color:Color(0x22000000))]),child:Row(children:[Expanded(child:Text('${cart.values.fold<int>(0,(a,b)=>a+b)} منتج  •  الدفع من المحفظة',style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800))),FilledButton(onPressed:checkout?null:checkoutCart,child:Text(checkout?'...':'إتمام الطلب'))]))));}
}

class _ProductCard extends StatelessWidget{const _ProductCard({required this.product,required this.quantity,required this.onAdd,required this.onRemove});final Product product;final int quantity;final VoidCallback onAdd,onRemove;@override Widget build(BuildContext context){final price=product.salePrice??product.price;return Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(17),border:Border.all(color:const Color(0xFFE2E8F0))),clipBehavior:Clip.antiAlias,child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Expanded(child:product.image!=null?Image.network(product.image!,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.image_not_supported,size:44,color:Colors.black26)):const Center(child:Icon(Icons.image_outlined,size:44,color:Colors.black26))),Padding(padding:const EdgeInsets.fromLTRB(9,8,9,4),child:Text(product.name,maxLines:2,overflow:TextOverflow.ellipsis,textAlign:TextAlign.right,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w900))),Padding(padding:const EdgeInsets.symmetric(horizontal:9),child:Text('${price.toStringAsFixed(0)} ${product.currency}',textAlign:TextAlign.right,style:const TextStyle(color:AppColors.burgundy,fontSize:13,fontWeight:FontWeight.w900))),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[IconButton(onPressed:quantity>0?onRemove:null,icon:const Icon(Icons.remove_circle_outline,size:20)),Text('$quantity',style:const TextStyle(fontWeight:FontWeight.w900)),IconButton(onPressed:product.stock>0?onAdd:null,icon:const Icon(Icons.add_circle,size:20,color:Colors.green))]) ]));}
}
