import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../core/app_controller.dart';
import '../widgets/common.dart';

class SupportScreen extends StatefulWidget{const SupportScreen({super.key});@override State<SupportScreen> createState()=>_SupportScreenState();}
class _SupportScreenState extends State<SupportScreen>{final msg=TextEditingController();Map<String,dynamic>? support;bool loading=false;@override void initState(){super.initState();load();}@override void dispose(){msg.dispose();super.dispose();}
Future<void>load()async{try{final s=await context.read<AppController>().api.support();setState(()=>support=s);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
Future<void>send()async{if(msg.text.trim().isEmpty)return;setState(()=>loading=true);try{final s=await context.read<AppController>().api.sendSupportMessage(msg.text.trim());msg.clear();setState(()=>support=s);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext context){final conversation=support?['conversation'];final messages=conversation is Map&&conversation['messages'] is List?conversation['messages'] as List:const [];return Scaffold(appBar:AppBar(title:const Text('التواصل مع الإدارة')),body:Column(children:[Expanded(child:messages.isEmpty?const Center(child:Text('لا توجد رسائل بعد.')):ListView.builder(padding:const EdgeInsets.all(12),itemCount:messages.length,itemBuilder:(_,i){final m=Map<String,dynamic>.from(messages[i]);final mine=m['senderRole']=='customer';return Align(alignment:mine?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.symmetric(horizontal:12,vertical:9),constraints:const BoxConstraints(maxWidth:320),decoration:BoxDecoration(color:mine?AppColors.burgundy:Colors.white,borderRadius:BorderRadius.circular(15),border:Border.all(color:const Color(0xFFE2E8F0))),child:Text('${m['body']??''}',style:TextStyle(fontSize:11,color:mine?Colors.white:Colors.black87,fontWeight:FontWeight.w700)));})),SafeArea(child:Container(padding:const EdgeInsets.all(10),decoration:const BoxDecoration(color:Colors.white,boxShadow:[BoxShadow(blurRadius:8,color:Color(0x18000000))]),child:Row(children:[Expanded(child:TextField(controller:msg,minLines:1,maxLines:3,decoration:const InputDecoration(hintText:'اكتب رسالتك...',isDense:true))),const SizedBox(width:7),IconButton(onPressed:loading?null:send,style:IconButton.styleFrom(backgroundColor:AppColors.burgundy,foregroundColor:Colors.white),icon:const Icon(Icons.send_rounded,size:19))]))) ]));}
