import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../core/app_controller.dart';
import '../widgets/common.dart';

class TransferScreen extends StatefulWidget{const TransferScreen({super.key});@override State<TransferScreen> createState()=>_TransferScreenState();}
class _TransferScreenState extends State<TransferScreen>{final receiver=TextEditingController();final amount=TextEditingController();final message=TextEditingController();Map<String,dynamic>? found;bool loading=false;@override void dispose(){receiver.dispose();amount.dispose();message.dispose();super.dispose();}
Future<void>lookup()async{if(receiver.text.trim().isEmpty)return;setState(()=>loading=true);try{final r=await context.read<AppController>().recipientLookup(receiver.text.trim());setState(()=>found=r);}catch(e){setState(()=>found=null);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>loading=false);}}
Future<void>submit()async{final a=double.tryParse(amount.text);if(found==null||a==null||a<=0)return;setState(()=>loading=true);try{final app=context.read<AppController>();final gift=await app.api.createGift(receiverPhone:receiver.text.trim(),amount:a,message:message.text);final id=int.tryParse('${gift['id']??0}');if(id!=null&&id>0)await app.api.confirmGift(id);await app.refreshWalletAndReports();if(mounted)showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('تم التحويل'),content:Text('تم إرسال ${a.toStringAsFixed(2)} ر.ي إلى ${found!['receiver_name']??receiver.text}\nالمرجع: ${gift['id']??'-'}'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('موافق'))]));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('تحويل لمشترك')),body:ListView(padding:const EdgeInsets.all(12),children:[PageCard(child:Column(children:[TextField(controller:receiver,keyboardType:TextInputType.phone,textDirection:TextDirection.ltr,decoration:const InputDecoration(labelText:'رقم المستلم',prefixIcon:Icon(Icons.person_search))),const SizedBox(height:8),SizedBox(width:double.infinity,child:OutlinedButton(onPressed:loading?null:lookup,child:const Text('فحص المستلم')))])),if(found!=null)...[const SizedBox(height:8),PageCard(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('${found!['receiver_name']??''}',style:const TextStyle(fontWeight:FontWeight.w900)),Text('${found!['receiver_phone']??receiver.text}',textDirection:TextDirection.ltr),Text('الرصيد المتاح: ${found!['available_balance']??''} ر.ي',style:const TextStyle(color:AppColors.blue,fontWeight:FontWeight.w800))]))],const SizedBox(height:8),PageCard(child:Column(children:[TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'مبلغ التحويل',suffixText:'ر.ي')),const SizedBox(height:8),TextField(controller:message,maxLines:3,decoration:const InputDecoration(labelText:'رسالة اختيارية')),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:loading||found==null?null:submit,style:FilledButton.styleFrom(backgroundColor:Colors.amber.shade700),child:const Text('تأكيد التحويل',style:TextStyle(fontWeight:FontWeight.w900))))]))]));}
